# Generated by Django 5.0.6 on 2024-07-09 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_pictures_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
