# Generated by Django 5.0.6 on 2024-07-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_pictures_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
